before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/qrn
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: "checksums.txt"
brews:
  - tap:
      owner: winebarrel
      name: homebrew-qrn
    homepage: https://github.com/winebarrel/qrn
    description: qrn is a database load testing tool.
    license: MIT
    install: |
      bin.install 'qrn'
nfpms:
  - id: qrn-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    homepage: https://github.com/winebarrel/qrn
    description: qrn is a database load testing tool.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
