name: build
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.17.0"
      - uses: golangci/golangci-lint-action@v3
        with:
          args: -E misspell
      - run: make
